base_url = "https://rosettagit.org"
compile_sass = true
build_search_index = false

taxonomies = [
  {name = "categories"},
  {name = "languages"},
  {name = "tags"},
]

[markdown]
highlight_code = false # TODO: Re-enable
highlight_theme = "monokai"

[extra]
author = "Adrian Sieber"
blog_logo = "icon.png" #will appear on top header
blog_title = "RosettaGit" #will appear on top header after logo
header_links = [
  { name = "Tasks", url = "/tasks" },
  { name = "Drafts", url = "/drafts" },
  { name = "Languages", url = "/languages" },
  { name = "Tags", url = "/tags"},
]

paginate_by = 20

## i18n words
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_relative_posts = "Relative Posts"
label_next = "Next"
label_previous = "Previous"
label_page = "Page"
label_of = "of"

og_image = "" # Image that will appear on social media
og_alt_image = "" # Alt for og_image
og_site_name = "" # Site Name for Open Graphic
keywords = "" # Keywords for SEO

educational_use = "knowledge share" # OPTIONAL
copyright_year = "2018" # OPTIONAL

fb_app_id = "???" # OPTIONAL, Facebook App Id to help in metrics
twitter_username = "@AdrianSieber" # OPTIONAL, Twitter User to help with metrics

[[extra.sidebar]]
name = "Contributing"
urls = [
  { name = "Code on GitHub", url = "https://github.com/ad-si/rosettagit" },
  { name = "Issues", url = "https://github.com/ad-si/rosettagit/issues" },
  { name = "Changelog", url = "https://github.com/ad-si/rosettagit/blob/changelog.md" },
]

[[extra.sidebar]]
name = "Special Pages"
urls = [
  { name = "Similar Sites", url = "/similar-sites" },
  { name = "Online Execution", url = "/online-execution" },
]
